/* populate all the lookup table values first
since they are parent tables to several other tables */

INSERT INTO LOOKUP_STATES VALUES
('AL','Alabama'),
('AK','Alaska'),
('AZ','Arizona'),
('AR','Arkansas'),
('CA','California'),
('CO','Colorado'),
('CT','Connecticut'),
('DE','Delaware'),
('DC','District of Columbia'),
('FL','Florida'),
('GA','Georgia'),
('HI','Hawaii'),
('ID','Idaho'),
('IL','Illinois'),
('IN','Indiana'),
('IA','Iowa'),
('KS','Kansas'),
('KY','Kentucky'),
('LA','Louisiana'),
('ME','Maine'),
('MT','Montana'),
('NE','Nebraska'),
('NV','Nevada'),
('NH','New Hampshire'),
('NJ','New Jersey'),
('NM','New Mexico'),
('NY','New York'),
('NC','North Carolina'),
('ND','North Dakota'),
('OH','Ohio'),
('OK','Oklahoma'),
('OR','Oregon'),
('MD','Maryland'),
('MA','Massachusetts'),
('MI','Michigan'),
('MN','Minnesota'),
('MS','Mississippi'),
('MO','Missouri'),
('PA','Pennsylvania'),
('RI','Rhode Island'),
('SC','South Carolina'),
('SD','South Dakota'),
('TN','Tennessee'),
('TX','Texas'),
('UT','Utah'),
('VT','Vermont'),
('VA','Virginia'),
('WA','Washington'),
('WV','West Virginia'),
('WI','Wisconsin'),
('WY','Wyoming');

INSERT INTO LOOKUP_COUNTRIES VALUES
('AF','Afghanistan'),
('AL','Albania'),
('DZ','Algeria'),
('AS','American Samoa'),
('AD','Andorra'),
('AO','Angola'),
('AI','Anguilla'),
('AQ','Antarctica'),
('AG','Antigua and Barbuda'),
('AR','Argentina'),
('AM','Armenia'),
('AW','Aruba'),
('AU','Australia'),
('AT','Austria'),
('AZ','Azerbaijan'),
('BS','Bahamas'),
('BH','Bahrain'),
('BD','Bangladesh'),
('BB','Barbados'),
('BY','Belarus'),
('BE','Belgium'),
('BZ','Belize'),
('BJ','Benin'),
('BM','Bermuda'),
('BT','Bhutan'),
('BO','Bolivia, Plurinational State of'),
('BQ','Bonaire, Sint Eustatius and Saba'),
('BA','Bosnia and Herzegovina'),
('BW','Botswana'),
('BV','Bouvet Island'),
('BR','Brazil'),
('IO','British Indian Ocean Territory'),
('BN','Brunei Darussalam'),
('BG','Bulgaria'),
('BF','Burkina Faso'),
('BI','Burundi'),
('KH','Cambodia'),
('CM','Cameroon'),
('CA','Canada'),
('CV','Cape Verde'),
('KY','Cayman Islands'),
('CF','Central African Republic'),
('TD','Chad'),
('CL','Chile'),
('CN','China'),
('CX','Christmas Island'),
('CC','Cocos Keeling) Islands'),
('CO','Colombia'),
('KM','Comoros'),
('CG','Congo'),
('CD','Congo, the Democratic Republic of the'),
('CK','Cook Islands'),
('CR','Costa Rica'),
('CI','Cote d''Ivoire'),
('HR','Croatia'),
('CU','Cuba'),
('CY','Cyprus'),
('CZ','Czech Republic'),
('DK','Denmark'),
('DJ','Djibouti'),
('DM','Dominica'),
('DO','Dominican Republic'),
('EC','Ecuador'),
('EG','Egypt'),
('SV','El Salvador'),
('GQ','Equatorial Guinea'),
('ER','Eritrea'),
('EE','Estonia'),
('ET','Ethiopia'),
('FK','Falkland Islands Malvinas)'),
('FO','Faroe Islands'),
('FJ','Fiji'),
('FI','Finland'),
('FR','France'),
('GF','French Guiana'),
('PF','French Polynesia'),
('TF','French Southern Territories'),
('GA','Gabon'),
('GM','Gambia'),
('GE','Georgia'),
('DE','Germany'),
('GH','Ghana'),
('GI','Gibraltar'),
('GR','Greece'),
('GL','Greenland'),
('GD','Grenada'),
('GP','Guadeloupe'),
('GU','Guam'),
('GT','Guatemala'),
('GG','Guernsey'),
('GN','Guinea'),
('GW','Guinea-Bissau'),
('GY','Guyana'),
('HT','Haiti'),
('HM','Heard Island and McDonald Islands'),
('VA','Holy See Vatican City State)'),
('HN','Honduras'),
('HK','Hong Kong'),
('HU','Hungary'),
('IS','Iceland'),
('IN','India'),
('ID','Indonesia'),
('IR','Iran, Islamic Republic of'),
('IQ','Iraq'),
('IE','Ireland'),
('IM','Isle of Man'),
('IL','Israel'),
('IT','Italy'),
('JM','Jamaica'),
('JP','Japan'),
('JE','Jersey'),
('JO','Jordan'),
('KZ','Kazakhstan'),
('KE','Kenya'),
('KI','Kiribati'),
('KP','Korea, Democratic People''s Republic of'),
('KR','Korea, Republic of'),
('KW','Kuwait'),
('KG','Kyrgyzstan'),
('LA','Lao People''s Democratic Republic'),
('LV','Latvia'),
('LB','Lebanon'),
('LS','Lesotho'),
('LR','Liberia'),
('LY','Libya'),
('LI','Liechtenstein'),
('LT','Lithuania'),
('LU','Luxembourg'),
('MO','Macao'),
('MK','Macedonia, the Former Yugoslav Republic of'),
('MG','Madagascar'),
('MW','Malawi'),
('MY','Malaysia'),
('MV','Maldives'),
('ML','Mali'),
('MT','Malta'),
('MH','Marshall Islands'),
('MQ','Martinique'),
('MR','Mauritania'),
('MU','Mauritius'),
('YT','Mayotte'),
('MX','Mexico'),
('FM','Micronesia, Federated States of'),
('MD','Moldova, Republic of'),
('MC','Monaco'),
('MN','Mongolia'),
('ME','Montenegro'),
('MS','Montserrat'),
('MA','Morocco'),
('MZ','Mozambique'),
('MM','Myanmar'),
('NA','Namibia'),
('NR','Nauru'),
('NP','Nepal'),
('NL','Netherlands'),
('NC','New Caledonia'),
('NZ','New Zealand'),
('NI','Nicaragua'),
('NE','Niger'),
('NG','Nigeria'),
('NU','Niue'),
('NF','Norfolk Island'),
('MP','Northern Mariana Islands'),
('NO','Norway'),
('OM','Oman'),
('PK','Pakistan'),
('PW','Palau'),
('PS','Palestine, State of'),
('PA','Panama'),
('PG','Papua New Guinea'),
('PY','Paraguay'),
('PE','Peru'),
('PH','Philippines'),
('PN','Pitcairn'),
('PL','Poland'),
('PT','Portugal'),
('PR','Puerto Rico'),
('QA','Qatar'),
('RO','Romania'),
('RU','Russian Federation'),
('RW','Rwanda'),
('SH','Saint Helena, Ascension and Tristan da Cunha'),
('KN','Saint Kitts and Nevis'),
('LC','Saint Lucia'),
('MF','Saint Martin French part)'),
('PM','Saint Pierre and Miquelon'),
('VC','Saint Vincent and the Grenadines'),
('WS','Samoa'),
('SM','San Marino'),
('ST','Sao Tome and Principe'),
('SA','Saudi Arabia'),
('SN','Senegal'),
('RS','Serbia'),
('SC','Seychelles'),
('SL','Sierra Leone'),
('SG','Singapore'),
('SX','Sint Maarten Dutch part)'),
('SK','Slovakia'),
('SI','Slovenia'),
('SB','Solomon Islands'),
('SO','Somalia'),
('ZA','South Africa'),
('GS','South Georgia and the South Sandwich Islands'),
('SS','South Sudan'),
('ES','Spain'),
('LK','Sri Lanka'),
('SD','Sudan'),
('SR','Suriname'),
('SJ','Svalbard and Jan Mayen'),
('SZ','Swaziland'),
('SE','Sweden'),
('CH','Switzerland'),
('SY','Syrian Arab Republic'),
('TW','Taiwan, Province of China'),
('TJ','Tajikistan'),
('TZ','Tanzania, United Republic of'),
('TH','Thailand'),
('TL','Timor-Leste'),
('TG','Togo'),
('TK','Tokelau'),
('TO','Tonga'),
('TT','Trinidad and Tobago'),
('TN','Tunisia'),
('TR','Turkey'),
('TM','Turkmenistan'),
('TC','Turks and Caicos Islands'),
('TV','Tuvalu'),
('UG','Uganda'),
('UA','Ukraine'),
('AE','United Arab Emirates'),
('GB','United Kingdom'),
('US','United States'),
('UM','United States Minor Outlying Islands'),
('UY','Uruguay'),
('UZ','Uzbekistan'),
('VU','Vanuatu'),
('VE','Venezuela, Bolivarian Republic of'),
('VN','Viet Nam'),
('VG','Virgin Islands, British'),
('VI','Virgin Islands, U.S.'),
('WF','Wallis and Futuna'),
('EH','Western Sahara'),
('YE','Yemen'),
('ZM','Zambia'),
('ZW','Zimbabwe');

INSERT INTO TAX_RATES VALUES (NewID(), 'Current tax rate as of 3/15/19', '6');

/* insert the values into the LOOKUP_EMPLOYEE_ROLES table
together with the EMPLOYEES table using variables */

DECLARE @OwnerID uniqueidentifier;
DECLARE @ManagerID uniqueidentifier;
DECLARE @ProcurementID uniqueidentifier;
DECLARE @SalesID uniqueidentifier;

SELECT @OwnerID = NewID();
SELECT @ManagerID = NewID();
SELECT @ProcurementID = NewID();
SELECT @SalesID = NewID();

INSERT INTO LOOKUP_EMPLOYEE_ROLES VALUES
(@OwnerID, 'Owner', 1),
(@ManagerID, 'Manager', 1),
(@ProcurementID, 'Procurement', 0),
(@SalesID, 'Sales', 0);

INSERT INTO EMPLOYEES VALUES
(
	NewID(),
	'Ronald',
	'Jacobs',
	@OwnerID,
	'2/10/2005',
	1,
	'68853 Bultman Hill',
	NULL,
	'St Paul',
	'MN',
	'55102',
	'652-332-1405',
	'rjacobs@jamesriverjewelry.com',
	'1/30/18 9:25:32 AM',
	'2/15/18 1:38:54 PM'
),
(
	NewID(),
	'Deborah',
	'Jacobs',
	@OwnerID,
	'2/10/2005',
	1,
	'68853 Bultman Hill',
	NULL,
	'St Paul',
	'MN',
	'55102',
	'652-332-1507',
	'djacobs@jamesriverjewelry.com',
	'1/30/18 9:25:33 AM',
	'4/22/18 2:15:54 PM'
),
(
	NewID(),
	'Martin',
	'Jacobs',
	@ManagerID,
	'2/14/2005',
	1,
	'444 Elka Center',
	NULL,
	'St Paul',
	'MN',
	'55102',
	'652-342-5039',
	'mjacobs@jamesriverjewelry.com',
	'1/30/18 9:25:34 AM',
	'1/30/18 9:25:34 AM'
),
(
	NewID(),
	'Thompson',
	'Scott',
	@ManagerID,
	'2/14/2005',
	1,
	'2 Sutteridge Road',
	'Apt 205B',
	'St Paul',
	'MN',
	'55103',
	'652-209-3921',
	'sthompson@jamesriverjewelry.com',
	'1/30/18 9:25:35 AM',
	'1/30/18 9:25:35 AM'
),
(
	NewID(),
	'Schuster',
	'Terry',
	@ProcurementID,
	'2/20/2005',
	1,
	'9125 Shelley Road',
	NULL,
	'St Paul',
	'MN',
	'55103',
	'652-845-0923',
	'tschuster@jamesriverjewelry.com',
	'1/30/18 9:25:36 AM',
	'1/30/18 9:25:36 AM'
),
(
	NewID(),
	'Evans',
	'Michael',
	@SalesID,
	'2/24/2005',
	1,
	'9125 Shelley Road',
	NULL,
	'St Paul',
	'MN',
	'55103',
	'652-845-0923',
	'mevans@jamesriverjewelry.com',
	'1/30/18 9:25:37 AM',
	'1/30/18 9:25:37 AM'
),
(
	NewID(),
	'Banks',
	'Holly',
	@SalesID,
	'5/12/2007',
	1,
	'19460 Waywood Road',
	NULL,
	'St Paul',
	'MN',
	'55103',
	'652-845-0923',
	'hbanks@jamesriverjewelry.com',
	'1/30/18 9:25:38 AM',
	'3/19/18 2:18:48 PM'
),
(
	NewID(),
	'Vickers',
	'Martha',
	@SalesID,
	'8/11/2010',
	1,
	'6157 Norway Maple Alley',
	NULL,
	'St Paul',
	'MN',
	'55103',
	'652-530-3294',
	'mvickers@jamesriverjewelry.com',
	'1/30/18 9:25:39 AM',
	'1/30/18 9:25:39 AM'
);
GO


